@baseUrl = http://localhost:3000/api
@resourceName=products

# Products

# @name getAllProducts
GET {{baseUrl}}/{{resourceName}}

###
# @name getOneProduct
GET {{baseUrl}}/{{resourceName}}/5vZpXep

###
# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?color=orchid&price_gte=300

###
# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?name_like=fantastic

###
# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=5

###
# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=asc

### 
# @name addNewProduct
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "categoryId": "cc4e9288-870a-40bd-91ba-bb743eb39728",
    "name": "Avatar",
    "color": "bblue",
    "price": 999,
    "description": "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    "thumbnailUrl": "http://placeimg.com/400/400"
  }

### 
# @name updateProduct
PATCH  {{baseUrl}}/{{resourceName}}/5vZpXep
Content-Type: application/json

{
    "name": "Avatar 2",
    "color": "blue",
    "price": 1000
  }

### 
# @name removeProduct
DELETE  {{baseUrl}}/{{resourceName}}/5